----------------------------------------------------------------------
-- ProfessionBuddy  --  Data/Forever/Fishing.lua
-- Fishing recipe data for WoW: Forever, build 1.60.1.70334.
--
-- GENERATED by tools/bake_forever_db2.py. Do not hand-edit.
-- Keyed by recipe name, like the TBC data. skillRange[1] is false
-- where the learn level is not known yet. learnFrom says where each
-- learn level came from.
----------------------------------------------------------------------

local recipes = {
    ["Fish Bowl"] = {
        spellID    = 1229745,
        itemID     = 279967,
        skillReq   = 20,
        learnFrom  = "trainer capture",
        category   = "Camping",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 6291, count = 1, name = "Raw Brilliant Smallfish" },
            { itemID = 3371, count = 1, name = "Empty Vial" },
        },
    },
    ["Fishing Hut"] = {
        spellID    = 1262998,
        itemID     = 279966,
        skillReq   = 300,
        learnFrom  = "recipe item",
        category   = "Camping",
        teachItems = { 273119 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Fishing Hut" } },
        reagents   = {
            { itemID = 4470, count = 5, name = "Simple Wood" },
            { itemID = 14048, count = 2, name = "Bolt of Runecloth" },
            { itemID = 273295, count = 1, name = "Seasonal Fish Steaks" },
        },
    },
    ["Fishing Rack"] = {
        spellID    = 1262990,
        itemID     = 279965,
        skillReq   = 140,
        learnFrom  = "recipe item",
        category   = "Camping",
        teachItems = { 273141 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Fishing Rack" } },
        reagents   = {
            { itemID = 4470, count = 2, name = "Simple Wood" },
            { itemID = 8925, count = 1, name = "Crystal Vial" },
            { itemID = 8365, count = 2, name = "Raw Mithril Head Trout" },
        },
    },
}

ProfBuddy.RecipeDB:RegisterProfession("Fishing", recipes)
