----------------------------------------------------------------------
-- ProfessionBuddy  --  Data/Forever/Herbalism.lua
-- Herbalism recipe data for WoW: Forever, build 1.60.1.70009.
--
-- GENERATED by tools/bake_forever_db2.py. Do not hand-edit.
-- Keyed by recipe name, like the TBC data. skillRange[1] is false
-- where the learn level is not known yet. learnFrom says where each
-- learn level came from.
----------------------------------------------------------------------

local recipes = {
    ["Gardening"] = {
        spellID    = 1278062,
        itemID     = 0,
        skillReq   = 1,
        learnFrom  = "automatic",
        category   = "Camping",
        sources    = { { method = "automatic", faction = "Both" } },
    },
    ["Greenhouse"] = {
        spellID    = 1262980,
        itemID     = 279964,
        skillReq   = 140,
        learnFrom  = "recipe item",
        skillRange = { 140, 140, 142, 145 },
        category   = "Camping",
        teachItems = { 273106 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Greenhouse" } },
        reagents   = {
            { itemID = 4470, count = 2, name = "Simple Wood" },
            { itemID = 8836, count = 1, name = "Arthas' Tears" },
            { itemID = 8831, count = 1, name = "Purple Lotus" },
        },
    },
    ["Incense Candle"] = {
        spellID    = 1229705,
        itemID     = 279962,
        skillReq   = 20,
        learnFrom  = "trainer capture",
        skillRange = { 20, 20, 22, 25 },
        category   = "Camping",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2447, count = 1, name = "Peacebloom" },
            { itemID = 765, count = 1, name = "Silverleaf" },
        },
    },
    ["Seed Hybridizer"] = {
        spellID    = 1263070,
        itemID     = 279947,
        skillReq   = 300,
        learnFrom  = "recipe item",
        skillRange = { 300, 300, 300, 300 },
        category   = "Camping",
        teachItems = { 273120 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Seed Hybridizer" } },
        reagents   = {
            { itemID = 13465, count = 4, name = "Mountain Silversage" },
            { itemID = 8925, count = 1, name = "Crystal Vial" },
            { itemID = 14047, count = 2, name = "Runecloth" },
        },
    },
}

ProfBuddy.RecipeDB:RegisterProfession("Herbalism", recipes)
