----------------------------------------------------------------------
-- ProfessionBuddy  --  Data/Forever/Mining.lua
-- Mining recipe data for WoW: Forever, build 1.60.1.70009.
--
-- GENERATED by tools/bake_forever_db2.py. Do not hand-edit.
-- Keyed by recipe name, like the TBC data. skillRange[1] is false
-- where the learn level is not known yet. learnFrom says where each
-- learn level came from.
----------------------------------------------------------------------

local recipes = {
    ["Lodestone"] = {
        spellID    = 1230161,
        itemID     = 279960,
        skillReq   = 20,
        learnFrom  = "trainer capture",
        skillRange = { 20, 20, 22, 25 },
        category   = "Camping",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2835, count = 1, name = "Rough Stone" },
            { itemID = 2840, count = 1, name = "Copper Bar" },
        },
    },
    ["Molten Foundry"] = {
        spellID    = 1263071,
        itemID     = 279952,
        skillReq   = 300,
        learnFrom  = "recipe item",
        skillRange = { 300, 300, 300, 300 },
        category   = "Camping",
        teachItems = { 273122 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Molten Foundry" } },
        reagents   = {
            { itemID = 12359, count = 5, name = "Thorium Bar" },
            { itemID = 12365, count = 2, name = "Dense Stone" },
            { itemID = 6037, count = 1, name = "Truesilver Bar" },
        },
    },
    ["Rock Garden"] = {
        spellID    = 1262975,
        itemID     = 279948,
        skillReq   = 140,
        learnFrom  = "recipe item",
        skillRange = { 140, 140, 142, 145 },
        category   = "Camping",
        teachItems = { 273097 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Rock Garden" } },
        reagents   = {
            { itemID = 2838, count = 2, name = "Heavy Stone" },
            { itemID = 2772, count = 1, name = "Iron Ore" },
            { itemID = 2842, count = 1, name = "Silver Bar" },
        },
    },
    ["Smelt Azerothium"] = {
        spellID    = 1249637,
        itemID     = 249726,
        skillReq   = 275,
        learnFrom  = "trainer capture",
        skillRange = { 275, 275, 275, 275 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 249426, count = 2, name = "Pitchblende" },
            { itemID = 3857, count = 1, name = "Coal" },
        },
    },
    ["Smelt Bronze"] = {
        spellID    = 2659,
        itemID     = 2841,
        yield      = 2,
        skillReq   = 65,
        learnFrom  = "trainer capture",
        skillRange = { 65, 65, 90, 115 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2840, count = 1, name = "Copper Bar" },
            { itemID = 3576, count = 1, name = "Tin Bar" },
        },
    },
    ["Smelt Copper"] = {
        spellID    = 2657,
        itemID     = 2840,
        skillReq   = 1,
        learnFrom  = "automatic",
        skillRange = { 1, 25, 47, 70 },
        category   = "Smelted Bars",
        sources    = { { method = "automatic", faction = "Both" } },
        reagents   = {
            { itemID = 2770, count = 1, name = "Copper Ore" },
        },
    },
    ["Smelt Dark Iron"] = {
        spellID    = 14891,
        itemID     = 11371,
        skillRange = { false, 230, 230, 230 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 11370, count = 8, name = "Dark Iron Ore" },
        },
    },
    ["Smelt Elementium"] = {
        spellID    = 22967,
        itemID     = 17771,
        skillRange = { false, 310, 315, 320 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 18562, count = 1, name = "Elementium Ore" },
            { itemID = 12360, count = 10, name = "Arcanite Bar" },
            { itemID = 17010, count = 1, name = "Fiery Core" },
            { itemID = 18567, count = 3, name = "Elemental Flux" },
        },
    },
    ["Smelt Gold"] = {
        spellID    = 3308,
        itemID     = 3577,
        skillReq   = 155,
        learnFrom  = "trainer capture",
        skillRange = { 155, 170, 177, 185 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2776, count = 1, name = "Gold Ore" },
        },
    },
    ["Smelt Heavy Thorium"] = {
        spellID    = 1306126,
        itemID     = 251291,
        skillReq   = 300,
        learnFrom  = "trainer capture",
        skillRange = { 300, 300, 307, 315 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 248815, count = 1, name = "Heavy Thorium Ore" },
        },
    },
    ["Smelt Iron"] = {
        spellID    = 3307,
        itemID     = 3575,
        skillReq   = 125,
        learnFrom  = "trainer capture",
        skillRange = { 125, 130, 135, 140 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2772, count = 1, name = "Iron Ore" },
        },
    },
    ["Smelt Mithril"] = {
        spellID    = 10097,
        itemID     = 3860,
        skillReq   = 175,
        learnFrom  = "trainer capture",
        skillRange = { 175, 175, 175, 175 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 3858, count = 1, name = "Mithril Ore" },
        },
    },
    ["Smelt Silver"] = {
        spellID    = 2658,
        itemID     = 2842,
        skillReq   = 75,
        learnFrom  = "trainer capture",
        skillRange = { 75, 100, 112, 125 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2775, count = 1, name = "Silver Ore" },
        },
    },
    ["Smelt Steel"] = {
        spellID    = 3569,
        itemID     = 3859,
        skillReq   = 165,
        learnFrom  = "trainer capture",
        skillRange = { 165, 165, 165, 165 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 3575, count = 1, name = "Iron Bar" },
            { itemID = 3857, count = 1, name = "Coal" },
        },
    },
    ["Smelt Thorium"] = {
        spellID    = 16153,
        itemID     = 12359,
        skillReq   = 250,
        learnFrom  = "trainer capture",
        skillRange = { 250, 250, 250, 250 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 10620, count = 1, name = "Thorium Ore" },
        },
    },
    ["Smelt Tin"] = {
        spellID    = 3304,
        itemID     = 3576,
        skillReq   = 65,
        learnFrom  = "trainer capture",
        skillRange = { 65, 50, 62, 75 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2771, count = 1, name = "Tin Ore" },
        },
    },
    ["Smelt Truesilver"] = {
        spellID    = 10098,
        itemID     = 6037,
        skillReq   = 230,
        learnFrom  = "trainer capture",
        skillRange = { 230, 230, 230, 230 },
        category   = "Smelted Bars",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 7911, count = 1, name = "Truesilver Ore" },
        },
    },
}

ProfBuddy.RecipeDB:RegisterProfession("Mining", recipes)
