----------------------------------------------------------------------
-- ProfessionBuddy  --  Data/Forever/RandomStats.lua
-- Crafted items that roll random stats on WoW: Forever, build 1.60.1.70334.
-- The game shows "<Random additional stats>" (ITEM_RANDOM_ENCHANT) only
-- on the trade-skill result, so PB appends it for these items, as it
-- does on TBC Anniversary (Data/RandomEnchant.lua). An item rolls
-- random stats when Forever gives it an item bonus tree (ItemXBonusTree).
--
-- GENERATED by tools/bake_forever_db2.py. Do not hand-edit.
----------------------------------------------------------------------
ProfBuddy = ProfBuddy or {}
ProfBuddy.RandomEnchantItems = {
    [3474] = true, -- Gemmed Copper Gauntlets
    [8210] = true, -- Wild Leather Shoulders
    [8211] = true, -- Wild Leather Vest
    [8212] = true, -- Wild Leather Leggings
    [8213] = true, -- Wild Leather Boots
    [8214] = true, -- Wild Leather Helmet
    [8215] = true, -- Wild Leather Cloak
    [10504] = true, -- Green Lens
    [20039] = true, -- Dark Iron Boots
    [280306] = true, -- Whimsical Waistwrap
    [280307] = true, -- Gizmo Girdle
    [280308] = true, -- Clanking Cord
    [280309] = true, -- Serrated Strap
    [280310] = true, -- Floppy Goggles
    [280311] = true, -- Bent Goggles
    [280312] = true, -- Stuckbutton Goggles
    [280313] = true, -- Dented Goggles
}
