----------------------------------------------------------------------
-- ProfessionBuddy  --  Data/Forever/Skinning.lua
-- Skinning recipe data for WoW: Forever, build 1.60.1.70009.
--
-- GENERATED by tools/bake_forever_db2.py. Do not hand-edit.
-- Keyed by recipe name, like the TBC data. skillRange[1] is false
-- where the learn level is not known yet. learnFrom says where each
-- learn level came from.
----------------------------------------------------------------------

local recipes = {
    ["Camp Chair"] = {
        spellID    = 1229517,
        itemID     = 279979,
        skillReq   = 20,
        learnFrom  = "trainer capture",
        skillRange = { 20, 20, 22, 25 },
        category   = "Camping",
        sources    = { { method = "trainer", faction = "Both" } },
        reagents   = {
            { itemID = 2318, count = 3, name = "Light Leather" },
            { itemID = 4470, count = 2, name = "Simple Wood" },
        },
    },
    ["Field Guide"] = {
        spellID    = 1262985,
        itemID     = 279969,
        skillReq   = 140,
        learnFrom  = "recipe item",
        skillRange = { 140, 140, 142, 145 },
        category   = "Camping",
        teachItems = { 273098 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Field Guide" } },
        reagents   = {
            { itemID = 2319, count = 3, name = "Medium Leather" },
            { itemID = 5784, count = 2, name = "Slimy Murloc Scale" },
            { itemID = 2321, count = 1, name = "Fine Thread" },
        },
    },
    ["Tanning"] = {
        spellID    = 1278068,
        itemID     = 0,
        skillReq   = 1,
        learnFrom  = "automatic",
        category   = "Camping",
        sources    = { { method = "automatic", faction = "Both" } },
    },
    ["Trapper's Workbench"] = {
        spellID    = 1262982,
        itemID     = 279938,
        skillReq   = 300,
        learnFrom  = "recipe item",
        skillRange = { 300, 300, 300, 300 },
        category   = "Camping",
        teachItems = { 273109 },
        sources    = { { method = "undetermined", faction = "Both", detail = "Blueprint: Trapper's Workbench" } },
        reagents   = {
            { itemID = 4470, count = 2, name = "Simple Wood" },
            { itemID = 4234, count = 4, name = "Heavy Leather" },
            { itemID = 3575, count = 1, name = "Iron Bar" },
        },
    },
}

ProfBuddy.RecipeDB:RegisterProfession("Skinning", recipes)
